### ISSUE TITLE
How to write values if I want to query multiple fields

### ISSUE THREAD

**Issue by tangxiaoran** [Corundex/database_exporter#3]
If I want to query how to write values for multiple fields, it seems that values only supports one field。
exp:

metric_name: oracle_tablespace_detail
type: gauge
help: 'oracle_tablespace_detail.'
values:
free
usage
total
key_labels:
tablespace_name
autoextend
query: |
......................................................
error:
[root@localhost database_exporter]# ./database_exporter -config.file /usr/local/database_exporter/database_exporter/config/oracle_exporter.yml
I0312 10:24:03.484394 32528 main.go:53] Starting Database Exporter (version=, branch=, revision=) (go=go1.10.3, user=, date=)
I0312 10:24:03.484992 32528 config.go:18] Loading configuration from /usr/local/database_exporter/database_exporter/config/oracle_exporter.yml
F0312 10:24:03.488097 32528 main.go:57] Error creating exporter: value_label must be defined for metric with multiple values "oracle_tablespace_detail"
goroutine 1 [running]:

**Comment by vahriin** [comment]
Faced the same issue, did you resolve it?
